### ISSUE TITLE
RuntimeError in demos

### ISSUE THREAD

**Issue by e-aranda** [Juanlu001/fenics-recipes#34] opened 2015-10-15 15:59 UTC
Hi,

I have installed fenics using conda and when I try some demos from fenics I find the following error:

```
RuntimeError: In instant.recompile: The module did not compile with command 'make VERBOSE=1', see '/home/earanda/.instant/error/dolfin_compile_code_c8b988ab6016262c9eebd6dc8482b98c0cf05c33/compile.log'
```

Looking into the file compile.log there is:

```
 make[2]: *** No rule to make target '/usr/lib/gcc/x86_64-linux-gnu/4.8/libgfortran.so', needed by '_dolfin_compile_code_c8b988ab6016262c9eebd6dc8482b98c0cf05c33.so'.  
```

And checking my system, I realize that I have not gcc in 4.8 version but 4.9 and 4.9.2. I don't  know what to do.
At the beginning of compile.log, the C compiler is correctly identified as 4.9.2

**Comment by astrojuanlu** [comment] 2015-10-15 16:07
Hello @e-aranda, thanks for reporting this issue. This is probably a duplicate of #31, since right now the packages are not completely portable and depend on having a certain path of the gfotran 4.8 libraries. I am waiting for a fix from upstream, in the meanwhile all I can tell you is to downgrade your compiler.

**Comment by astrojuanlu** [comment] 2015-10-16 08:37
Closing this as a duplicate.

**Closed as completed by astrojuanlu** 2015-10-16 08:37 UTC
Labels: bug
