### ISSUE TITLE
DOLFIN swig version is not the same as extension module swig version: '3.0.5' != '3.0.7' .

### ISSUE THREAD

**Issue by dlouk** [Juanlu001/fenics-recipes#27] opened 2015-09-02 09:22 UTC
Hi,

first of all many thanks for all the work and effort you have put in this.

I encounter the following error when I try to run an example script called run_lshape_DL.py, using the Anaconda distribution and FEniCS on Ubuntu 14.04 LTS. The error happens also with any of the examples provided in the FEniCS tutorial webpage.

``` python
Traceback (most recent call last):
  File "run_lshape_DL.py", line 32, in <module>
    ue = Expression("sin(pi*x[0])*sin(pi*x[1])",degree=2)
  File "/home/dimitrios/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/functions/expression.py", line 602, in __new__
    mpi_comm=mpi_comm)
  File "/home/dimitrios/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/compilemodules/expressions.py", line 217, in compile_expressions
    mpi_comm=mpi_comm)
  File "/home/dimitrios/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/compilemodules/expressions.py", line 145, in compile_expression_code
    mpi_comm=mpi_comm)
  File "/home/dimitrios/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/compilemodules/jit.py", line 64, in mpi_jit
    return local_jit(*args, **kwargs)
  File "/home/dimitrios/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/compilemodules/compilemodule.py", line 416, in compile_extension_module
    check_swig_version(compiled_module)
  File "/home/dimitrios/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/compilemodules/compilemodule.py", line 249, in check_swig_version
    (cpp.__swigversion__, compiled_module.swigversion))
  File "/home/dimitrios/anaconda/envs/fenics27/lib/python2.7/site-packages/dolfin/cpp/common.py", line 2611, in dolfin_error
    return _common.dolfin_error(location, task, reason)

RuntimeError: 
*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics@fenicsproject.org
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to compiling extension module.
*** Reason:  Incompatible swig versions detected. DOLFIN swig version is not the same as extension module swig version: '3.0.5' != '3.0.7' .
*** Where:   This error was encountered inside compilemodule.py.
*** Process: 0
*** 
*** DOLFIN version: 1.6.0
*** Git changeset:  
*** -------------------------------------------------------------------------
```

Any advice is welcome!

Dimitris

**Comment by astrojuanlu** [comment] 2015-09-02 09:35
Hi @dlouk, thanks for your nice comments :) You are totally right, I'm providing the wrong version of SWIG in my packages. I will try to fix that today, shouldn't take much time.

**Comment by astrojuanlu** [comment] 2015-09-06 09:22
I just uploaded new versions of dolfin and ffc which in principle specify the right swig version. Could you please try updating and see if the issue is gone? If it is we can close the issue :)

**Comment by dlouk** [comment] 2015-09-07 20:48
Sorry for the late reply. I am on a short vacation, so I will check first thing on Wednesday. Thanks for the update!

**Comment by dlouk** [comment] 2015-09-09 15:35
It seems to be working fine now. I guess that you can close the issue now.

**Comment by astrojuanlu** [comment] 2015-09-09 19:33
Perfect, thanks! :smile:

**Closed as completed by astrojuanlu** 2015-09-09 19:33 UTC
Labels: bug
