### ISSUE TITLE
link with PETSc fails

### ISSUE THREAD

**Issue by RafalSkolasinski** [Juanlu001/fenics-recipes#26] opened 2015-08-29 10:19 UTC
Hi, I just tried to do local build as readme says and I have following error:

```
ERROR: Unable to link with PETSc
ERROR: See "arch-linux2-c-debug/conf/configure.log" file for details
```

Also I had to do `conda instal jinja2' first.

**Comment by astrojuanlu** [comment] 2015-08-29 10:38
Hi! Could you specify which OS are you trying, attach `arch-linux2-c-debug/conf/configure.log` (maybe to http://gist.github.com) and at which step of the process did this happen? You can also try to build the packages individually, but I am sure that some of them were built successfully already.

**Comment by RafalSkolasinski** [comment] 2015-08-29 10:55
Here are last lines on my terminal: http://pastebin.com/4mvHxHiH
And here is 'configure.log file': http://pastebin.com/rnFEF91r

My operating system is ubuntu 14.04

**Comment by astrojuanlu** [comment] 2015-08-29 11:13
So the problem is with SLEPc, I will have to check that. I see in the config file that the PETSc directory is wrong, so perhaps that's the issue.

**Comment by astrojuanlu** [comment] 2015-08-29 11:45
Oh no, it was more subtle than that... See at the bottom of the config file:

`make: /usr/bin/sh: Command not found`

https://bitbucket.org/fenics-project/dolfin/issues/550/make-usr-bin-sh-command-not-found-in-fresh

If you have the time, would you please send a corresponding email to fenics-support@fenicsproject.org? I guess many people will encounter this issue... Closing.

**Closed as completed by astrojuanlu** 2015-08-29 11:45 UTC
