### ISSUE TITLE
 ImportError: No module named dolfin

### ISSUE THREAD

**Issue by akpeneajo** [Juanlu001/fenics-recipes#40] opened 2015-11-02 21:54 UTC
I have installed fenics on my ubuntu 14.04 system but whenever i try to import dolfin i get the following error. I have python installed. Please any help is greatly appreciated. Thanks.

**Comment by astrojuanlu** [comment] 2015-11-02 22:16
Hello @akpeneajo, can you check if your error is a duplicate of https://github.com/Juanlu001/fenics-recipes/issues/32? Please paste the output of `conda info -a` to have more information.

**Comment by akpeneajo** [comment] 2015-11-03 00:12
This is what I have Juanlu001

vivian@vivian-Latitude-E5510:~$ conda info -a
Current conda install:

```
         platform : linux-32
    conda version : 3.18.3
```

  conda-build version : 1.8.2
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : /home/vivian/anaconda  (writable)
  default environment : /home/vivian/anaconda
     envs directories : /home/vivian/anaconda/envs
        package cache : /home/vivian/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

# conda environments:

#
fenics27                 /home/vivian/anaconda/envs/fenics27
root                  \*  /home/vivian/anaconda

sys.version: 2.7.10 |Anaconda 2.1.0 (32-bit)| (defaul...
sys.prefix: /home/vivian/anaconda
sys.executable: /home/vivian/anaconda/bin/python
conda location: /home/vivian/anaconda/lib/python2.7/site-packages/conda
conda-build: /home/vivian/anaconda/bin/conda-build
conda-convert: /home/vivian/anaconda/bin/conda-convert
conda-develop: /home/vivian/anaconda/bin/conda-develop
conda-env: /home/vivian/anaconda/bin/conda-env
conda-index: /home/vivian/anaconda/bin/conda-index
conda-metapackage: /home/vivian/anaconda/bin/conda-metapackage
conda-pipbuild: /home/vivian/anaconda/bin/conda-pipbuild
conda-skeleton: /home/vivian/anaconda/bin/conda-skeleton
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
LD_LIBRARY_PATH: <not set>
PATH: /home/vivian/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PYTHONHOME: <not set>
PYTHONPATH: <not set>

License directories:
    /home/vivian/.continuum
    /home/vivian/anaconda/licenses
License files (license*.txt):
Package/feature end dates:

**Comment by akpeneajo** [comment] 2015-11-03 00:29
Hi Juanlu001, I tried to reinstall and below is that result of the command you asked me to run

vivian@vivian-Latitude-E5510:~$ conda info -a
Current conda install:

```
         platform : linux-32
    conda version : 3.18.3
```

  conda-build version : 1.8.2
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : /home/vivian/anaconda  (writable)
  default environment : /home/vivian/anaconda
     envs directories : /home/vivian/anaconda/envs
        package cache : /home/vivian/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

# conda environments:

#
fenics27                 /home/vivian/anaconda/envs/fenics27
root                  \*  /home/vivian/anaconda

sys.version: 2.7.10 |Anaconda 2.1.0 (32-bit)| (defaul...
sys.prefix: /home/vivian/anaconda
sys.executable: /home/vivian/anaconda/bin/python
conda location: /home/vivian/anaconda/lib/python2.7/site-packages/conda
conda-build: /home/vivian/anaconda/bin/conda-build
conda-convert: /home/vivian/anaconda/bin/conda-convert
conda-develop: /home/vivian/anaconda/bin/conda-develop
conda-env: /home/vivian/anaconda/bin/conda-env
conda-index: /home/vivian/anaconda/bin/conda-index
conda-metapackage: /home/vivian/anaconda/bin/conda-metapackage
conda-pipbuild: /home/vivian/anaconda/bin/conda-pipbuild
conda-skeleton: /home/vivian/anaconda/bin/conda-skeleton
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
LD_LIBRARY_PATH: <not set>
PATH: /home/vivian/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PYTHONHOME: <not set>
PYTHONPATH: <not set>

License directories:
    /home/vivian/.continuum
    /home/vivian/anaconda/licenses
License files (license*.txt):
Package/feature end dates:

**Comment by akpeneajo** [comment] 2015-11-03 00:40
Hi @Juanlu001 
SO i followed #32  and this is what I get after trying to import dolfin

vivian@vivian-Latitude-E5510:~$ from dolfin import *
from: can't read /var/mail/dolfin

**Comment by astrojuanlu** [comment] 2015-11-03 05:56
You have to open a Python interpreter first

**Comment by astrojuanlu** [comment] 2016-01-04 10:51
As there's no more input I'm closing this, please feel free to reopen if the problem persists.

**Closed as completed by astrojuanlu** 2016-01-04 10:51 UTC
